### ISSUE TITLE
Offset is out of bounds

### ISSUE THREAD

**Issue by nicolasduranl** [ip2location-nodejs/IP2Location#3]
I am getting this error:
```
/Users/nicolasduran/Desktop/projects/1doc3-api/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at readbin (/Users/nicolasduran/Desktop/projects/1doc3-api/node_modules/ip2location-nodejs/src/ip2location.js:98:17)
    at readstr (/Users/nicolasduran/Desktop/projects/1doc3-api/node_modules/ip2location-nodejs/src/ip2location.js:172:9)
    at IP2Location_query (/Users/nicolasduran/Desktop/projects/1doc3-api/node_modules/ip2location-nodejs/src/ip2location.js:377:17)
    at Object.IP2Location_get_all (/Users/nicolasduran/Desktop/projects/1doc3-api/node_modules/ip2location-nodejs/src/ip2location.js:492:3)
```

**Comment by nicolasduranl** [comment]
Just in case someone else get this error, it was caused because of an error downloading the .BIN file
